"""Deterministic US Market Rotation & Theme Flow engine."""

DATA_SCHEMA_VERSION = "1.2"
METHODOLOGY_VERSION = "1.2.0"
INSTRUCTION_VERSION = "1.6.0"
PUBLICATION_CONTRACT_VERSION = "1.1"
JUDGMENT_SCHEMA_VERSION = "1.0"
THEME_MASTER_SCHEMA_VERSION = "1.0"
